.OP
.HE
            ZMAÃ REGISTRATIOÎ ANÄ PERFORMANCÅ REPORÔ


PRODUCÔ NAMÅ/Version____________________TODAY'Ó DATE:__________

USEÒ NAME_______________________________PHONE:(___)____________

USEÒ ADDRESS___________________________________________________

            ___________________________________________________

USEÒ HARDWARÅ ¦ SOFTWARÅ SYSTEM:_______________________________

            ___________________________________________________

REPORÔ TYPEº                       PERFORMANCÅ IMPACT:

__ß Problem/Buç reporô             __ß Impairó Systeí Performance

__ß Suggesteä Enhancemenô          __ß Causeó Inconvenience

__ß Documenô Suggestioî            __ß Needó Enhancemenô (below)

__ß Registratioî foò updateó       __ß OTHEÒ ____________________


PROBLEÍ/ENHANCEMENT DESCRIPTION
(Pleaså  uså  thå  followinç spacå tï  describå  thå  probleí  oò 
proposeä enhancemenô aó clearlù anä conciselù aó yoõ can® Iæ it'ó 
á  problem¬  ho÷  caî iô bå reproduced¿  Pleaså  namå  anù  fileó 
involved» listingó meù bå quitå helpful® Whaô ió youò  diagnosis¿ 
Dï yoõ havå á curå oò work-arounä thaô yoõ caî offer?)

.paŠ